version: '3.8'

services:
  speed-checker:
    build: .
    container_name: speed-checker
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SPEED_CHECKER_DATABASE_DSN=/app/data/speedtest_results.db?_fk=1
      - SPEED_CHECKER_SERVER_HOST=0.0.0.0
      - SPEED_CHECKER_SERVER_PORT=8080
      - SPEED_CHECKER_TESTING_SPEEDTEST_INTERVAL=15m
      - SPEED_CHECKER_TESTING_IPERF_INTERVAL=10m
      - SPEED_CHECKER_TESTING_IPERF_DURATION=10
    restart: unless-stopped
    networks:
      - speed-checker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/dashboard"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

networks:
  speed-checker-network:
    driver: bridge

volumes:
  speed-checker-data:
    driver: local 