// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HostType.
const (
	Lan    HostType = "lan"
	Remote HostType = "remote"
	Vpn    HostType = "vpn"
)

// Defines values for IperfTestResultProtocol.
const (
	IperfTestResultProtocolTCP IperfTestResultProtocol = "TCP"
	IperfTestResultProtocolUDP IperfTestResultProtocol = "UDP"
)

// Defines values for IperfTestSubmissionProtocol.
const (
	IperfTestSubmissionProtocolTCP IperfTestSubmissionProtocol = "TCP"
	IperfTestSubmissionProtocolUDP IperfTestSubmissionProtocol = "UDP"
)

// DashboardData defines model for DashboardData.
type DashboardData struct {
	// RecentIperfTests Recent iperf test results
	RecentIperfTests []IperfTestResult `json:"recent_iperf_tests"`

	// RecentSpeedTests Recent speed test results
	RecentSpeedTests []SpeedTestResult `json:"recent_speed_tests"`
	Statistics       struct {
		// ActiveHosts Number of active hosts
		ActiveHosts *int `json:"active_hosts,omitempty"`

		// AvgDownloadMbps Average download speed over last 24h
		AvgDownloadMbps *float64 `json:"avg_download_mbps,omitempty"`

		// AvgUploadMbps Average upload speed over last 24h
		AvgUploadMbps *float64 `json:"avg_upload_mbps,omitempty"`

		// TotalIperfTests Total number of iperf tests
		TotalIperfTests *int `json:"total_iperf_tests,omitempty"`

		// TotalSpeedTests Total number of speed tests
		TotalSpeedTests *int `json:"total_speed_tests,omitempty"`
	} `json:"statistics"`
}

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code or type
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Host defines model for Host.
type Host struct {
	// Active Whether the host is active for testing
	Active *bool `json:"active,omitempty"`

	// CreatedAt When the host was created
	CreatedAt time.Time `json:"created_at"`

	// Description Optional description of the host
	Description *string `json:"description,omitempty"`

	// Hostname Hostname or IP address
	Hostname string `json:"hostname"`

	// Id Unique identifier for the host
	Id int `json:"id"`

	// Name Human-readable name for the host
	Name string `json:"name"`

	// Port Port number for iperf3 server
	Port int `json:"port"`

	// Type Type of host for categorizing network tests
	Type HostType `json:"type"`

	// UpdatedAt When the host was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// HostCreation defines model for HostCreation.
type HostCreation struct {
	// Active Whether the host is active for testing
	Active *bool `json:"active,omitempty"`

	// Description Optional description of the host
	Description *string `json:"description,omitempty"`

	// Hostname Hostname or IP address
	Hostname string `json:"hostname"`

	// Name Human-readable name for the host
	Name string `json:"name"`

	// Port Port number for iperf3 server
	Port int `json:"port"`

	// Type Type of host for categorizing network tests
	Type HostType `json:"type"`
}

// HostType Type of host for categorizing network tests
type HostType string

// HostUpdate defines model for HostUpdate.
type HostUpdate struct {
	// Active Whether the host is active for testing
	Active *bool `json:"active,omitempty"`

	// Description Optional description of the host
	Description *string `json:"description,omitempty"`

	// Hostname Hostname or IP address
	Hostname string `json:"hostname"`

	// Name Human-readable name for the host
	Name string `json:"name"`

	// Port Port number for iperf3 server
	Port int `json:"port"`

	// Type Type of host for categorizing network tests
	Type HostType `json:"type"`
}

// IperfTestResult defines model for IperfTestResult.
type IperfTestResult struct {
	// CreatedAt When the result was stored in the system
	CreatedAt time.Time `json:"created_at"`

	// DaemonId Identifier of the daemon that performed the test
	DaemonId string `json:"daemon_id"`

	// DurationSeconds Test duration in seconds
	DurationSeconds int `json:"duration_seconds"`

	// ErrorMessage Error message if test failed
	ErrorMessage *string `json:"error_message,omitempty"`
	Host         Host    `json:"host"`

	// HostId ID of the target host
	HostId int `json:"host_id"`

	// Id Unique identifier for the test result
	Id int `json:"id"`

	// MeanRttMs Mean round-trip time in milliseconds
	MeanRttMs *float64 `json:"mean_rtt_ms,omitempty"`

	// Protocol Protocol used for the test
	Protocol IperfTestResultProtocol `json:"protocol"`

	// ReceivedMbps Received throughput in Mbps
	ReceivedMbps float64 `json:"received_mbps"`

	// Retransmits Number of retransmitted packets
	Retransmits *float64 `json:"retransmits,omitempty"`

	// SentMbps Sent throughput in Mbps
	SentMbps float64 `json:"sent_mbps"`

	// Success Whether the test was successful
	Success *bool `json:"success,omitempty"`

	// Timestamp When the test was performed (RFC3339)
	Timestamp time.Time `json:"timestamp"`
}

// IperfTestResultProtocol Protocol used for the test
type IperfTestResultProtocol string

// IperfTestSubmission defines model for IperfTestSubmission.
type IperfTestSubmission struct {
	// DaemonId Identifier of the daemon that performed the test
	DaemonId string `json:"daemon_id"`

	// DurationSeconds Test duration in seconds
	DurationSeconds int `json:"duration_seconds"`

	// HostId ID of the target host
	HostId int `json:"host_id"`

	// MeanRttMs Mean round-trip time in milliseconds
	MeanRttMs *float64 `json:"mean_rtt_ms,omitempty"`

	// Protocol Protocol used for the test
	Protocol IperfTestSubmissionProtocol `json:"protocol"`

	// ReceivedMbps Received throughput in Mbps
	ReceivedMbps float64 `json:"received_mbps"`

	// Retransmits Number of retransmitted packets
	Retransmits *float64 `json:"retransmits,omitempty"`

	// SentMbps Sent throughput in Mbps
	SentMbps float64 `json:"sent_mbps"`

	// Timestamp When the test was performed (RFC3339)
	Timestamp time.Time `json:"timestamp"`
}

// IperfTestSubmissionProtocol Protocol used for the test
type IperfTestSubmissionProtocol string

// SpeedTestResult defines model for SpeedTestResult.
type SpeedTestResult struct {
	// CreatedAt When the result was stored in the system
	CreatedAt time.Time `json:"created_at"`

	// DaemonId Identifier of the daemon that performed the test
	DaemonId string `json:"daemon_id"`

	// DownloadMbps Download speed in Mbps
	DownloadMbps float64 `json:"download_mbps"`

	// ExternalIp External IP address used for the test
	ExternalIp *string `json:"external_ip,omitempty"`

	// Id Unique identifier for the test result
	Id int `json:"id"`

	// Isp Internet Service Provider
	Isp *string `json:"isp,omitempty"`

	// JitterMs Jitter in milliseconds
	JitterMs *float64 `json:"jitter_ms,omitempty"`

	// PingMs Ping latency in milliseconds
	PingMs float64 `json:"ping_ms"`

	// ResultUrl URL to full test results
	ResultUrl *string `json:"result_url,omitempty"`

	// ServerId Speed test server ID
	ServerId *string `json:"server_id,omitempty"`

	// ServerName Speed test server name
	ServerName *string `json:"server_name,omitempty"`

	// Timestamp When the test was performed (RFC3339)
	Timestamp time.Time `json:"timestamp"`

	// UploadMbps Upload speed in Mbps
	UploadMbps float64 `json:"upload_mbps"`
}

// SpeedTestSubmission defines model for SpeedTestSubmission.
type SpeedTestSubmission struct {
	// DaemonId Identifier of the daemon that performed the test
	DaemonId string `json:"daemon_id"`

	// DownloadMbps Download speed in Mbps
	DownloadMbps float64 `json:"download_mbps"`

	// ExternalIp External IP address used for the test
	ExternalIp *string `json:"external_ip,omitempty"`

	// Isp Internet Service Provider
	Isp *string `json:"isp,omitempty"`

	// JitterMs Jitter in milliseconds
	JitterMs *float64 `json:"jitter_ms,omitempty"`

	// PingMs Ping latency in milliseconds
	PingMs float64 `json:"ping_ms"`

	// ResultUrl URL to full test results
	ResultUrl *string `json:"result_url,omitempty"`

	// ServerId Speed test server ID
	ServerId *string `json:"server_id,omitempty"`

	// ServerName Speed test server name
	ServerName *string `json:"server_name,omitempty"`

	// Timestamp When the test was performed (RFC3339)
	Timestamp time.Time `json:"timestamp"`

	// UploadMbps Upload speed in Mbps
	UploadMbps float64 `json:"upload_mbps"`
}

// GetHostsParams defines parameters for GetHosts.
type GetHostsParams struct {
	// Type Filter by host type
	Type *HostType `form:"type,omitempty" json:"type,omitempty"`

	// Active Filter by active status
	Active *bool `form:"active,omitempty" json:"active,omitempty"`
}

// GetIperfTestsParams defines parameters for GetIperfTests.
type GetIperfTestsParams struct {
	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// StartTime Filter results after this timestamp (RFC3339)
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime Filter results before this timestamp (RFC3339)
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`

	// HostId Filter by host ID
	HostId *int `form:"host_id,omitempty" json:"host_id,omitempty"`

	// DaemonId Filter by daemon ID
	DaemonId *string `form:"daemon_id,omitempty" json:"daemon_id,omitempty"`
}

// GetSpeedTestsParams defines parameters for GetSpeedTests.
type GetSpeedTestsParams struct {
	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// StartTime Filter results after this timestamp (RFC3339)
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime Filter results before this timestamp (RFC3339)
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`

	// DaemonId Filter by daemon ID
	DaemonId *string `form:"daemon_id,omitempty" json:"daemon_id,omitempty"`
}

// AddHostJSONRequestBody defines body for AddHost for application/json ContentType.
type AddHostJSONRequestBody = HostCreation

// UpdateHostJSONRequestBody defines body for UpdateHost for application/json ContentType.
type UpdateHostJSONRequestBody = HostUpdate

// SubmitIperfTestJSONRequestBody defines body for SubmitIperfTest for application/json ContentType.
type SubmitIperfTestJSONRequestBody = IperfTestSubmission

// SubmitSpeedTestJSONRequestBody defines body for SubmitSpeedTest for application/json ContentType.
type SubmitSpeedTestJSONRequestBody = SpeedTestSubmission

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get dashboard data
	// (GET /dashboard)
	GetDashboard(ctx echo.Context) error
	// Get iperf test hosts
	// (GET /hosts)
	GetHosts(ctx echo.Context, params GetHostsParams) error
	// Add new host
	// (POST /hosts)
	AddHost(ctx echo.Context) error
	// Delete host
	// (DELETE /hosts/{hostId})
	DeleteHost(ctx echo.Context, hostId int) error
	// Get host by ID
	// (GET /hosts/{hostId})
	GetHost(ctx echo.Context, hostId int) error
	// Update host
	// (PUT /hosts/{hostId})
	UpdateHost(ctx echo.Context, hostId int) error
	// Get iperf test results
	// (GET /iperf/results)
	GetIperfTests(ctx echo.Context, params GetIperfTestsParams) error
	// Submit iperf test results
	// (POST /iperf/results)
	SubmitIperfTest(ctx echo.Context) error
	// Get speed test results
	// (GET /speedtest/results)
	GetSpeedTests(ctx echo.Context, params GetSpeedTestsParams) error
	// Submit speed test results
	// (POST /speedtest/results)
	SubmitSpeedTest(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDashboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboard(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboard(ctx)
	return err
}

// GetHosts converts echo context to params.
func (w *ServerInterfaceWrapper) GetHosts(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHostsParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameter("form", true, false, "active", ctx.QueryParams(), &params.Active)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter active: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHosts(ctx, params)
	return err
}

// AddHost converts echo context to params.
func (w *ServerInterfaceWrapper) AddHost(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddHost(ctx)
	return err
}

// DeleteHost converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteHost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "hostId" -------------
	var hostId int

	err = runtime.BindStyledParameterWithOptions("simple", "hostId", ctx.Param("hostId"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter hostId: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteHost(ctx, hostId)
	return err
}

// GetHost converts echo context to params.
func (w *ServerInterfaceWrapper) GetHost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "hostId" -------------
	var hostId int

	err = runtime.BindStyledParameterWithOptions("simple", "hostId", ctx.Param("hostId"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter hostId: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHost(ctx, hostId)
	return err
}

// UpdateHost converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateHost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "hostId" -------------
	var hostId int

	err = runtime.BindStyledParameterWithOptions("simple", "hostId", ctx.Param("hostId"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter hostId: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateHost(ctx, hostId)
	return err
}

// GetIperfTests converts echo context to params.
func (w *ServerInterfaceWrapper) GetIperfTests(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIperfTestsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time", ctx.QueryParams(), &params.StartTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_time: %s", err))
	}

	// ------------- Optional query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_time", ctx.QueryParams(), &params.EndTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_time: %s", err))
	}

	// ------------- Optional query parameter "host_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "host_id", ctx.QueryParams(), &params.HostId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter host_id: %s", err))
	}

	// ------------- Optional query parameter "daemon_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "daemon_id", ctx.QueryParams(), &params.DaemonId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter daemon_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIperfTests(ctx, params)
	return err
}

// SubmitIperfTest converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitIperfTest(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitIperfTest(ctx)
	return err
}

// GetSpeedTests converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpeedTests(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeedTestsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time", ctx.QueryParams(), &params.StartTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_time: %s", err))
	}

	// ------------- Optional query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_time", ctx.QueryParams(), &params.EndTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_time: %s", err))
	}

	// ------------- Optional query parameter "daemon_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "daemon_id", ctx.QueryParams(), &params.DaemonId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter daemon_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpeedTests(ctx, params)
	return err
}

// SubmitSpeedTest converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitSpeedTest(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitSpeedTest(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/dashboard", wrapper.GetDashboard)
	router.GET(baseURL+"/hosts", wrapper.GetHosts)
	router.POST(baseURL+"/hosts", wrapper.AddHost)
	router.DELETE(baseURL+"/hosts/:hostId", wrapper.DeleteHost)
	router.GET(baseURL+"/hosts/:hostId", wrapper.GetHost)
	router.PUT(baseURL+"/hosts/:hostId", wrapper.UpdateHost)
	router.GET(baseURL+"/iperf/results", wrapper.GetIperfTests)
	router.POST(baseURL+"/iperf/results", wrapper.SubmitIperfTest)
	router.GET(baseURL+"/speedtest/results", wrapper.GetSpeedTests)
	router.POST(baseURL+"/speedtest/results", wrapper.SubmitSpeedTest)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbfW8bN9L/KgSfB+gdIOvVah39dT67bXxNWiN20MOlhkDtjiQ2u+SW5MrRBf7uhyG5",
	"b1pqJad2kMMFKNBol+QMZ36c38xw/ZFGMs2kAGE0nX2kOlpDyuw/L5leLyRT8SUzDB9kSmagDAf7WkEE",
	"wsx5Bmo5N6Dd/Bh0pHhmuBR0Rt/YMcSOITiGKNB5YjTtUW4gtVP+X8GSzuj/DSpNBl6NwRXOvAVt3th5",
	"9KFHzTYDOqNMKbbF314PnQHEB/SwYz5Jjxuc2a2HNsxwbXik27ZikeEbmK9lULuf83QBisglceOIG9ej",
	"8IGlWQJ0Ni3FcWFgBQoFss1qHst7kUgWz9NFFlj5fAOKrYAUw7wF5AYUSZg2ZHy6rss5nZ71xz26lCpl",
	"hs5oLPNFArSULqymhfA8O0K0G3RI8OjsRf+7owQbaVjSjbpbHEJEadUKfg2jTs7Go5BdnYROPO1KqIDV",
	"kDCano7bEirsyMXvEBn7RMEfOVcQ09m7EKJ7oePWwNxda9Ue/V4pqdpojMEwnjhgxjHHPbHkujbEqBx6",
	"u/4sRxLAZUmxSkAuFHKbS1h1SCRjIFIRO6tmLLphCY8Zjp27BcqVtVFcrHDlFLRmK2iv/TJPmThRwGK2",
	"SMCrWIyuS7ldA/mmcWy+IUsOSUy4JoUXCBMxSXNtyAIII5nU3B5MD8OWYjsOLNQv5Id881JqYz2QJL8s",
	"6exdd/zB0RcKrHXoQ2/XoxG+gnjOTNsyv65BELN2UYXcM0386IZZxsPx6clwdDKa3o6GsyH+9y9aP5DM",
	"wInhKYS8wuO22LeC/5ED4TEIw5ccFFmi070ejVMSOoR5Fj9iRzak+Ckd25o8Zls7PuW4cM3ODRXbDr7z",
	"Li6dtocT3O6WDEkleO5+XYNZQ2U5hKmnCWtQ0AbVLRVYSJkAQ5A0F9o14i+ZP821xxjKQh6i14qnTG3J",
	"q/OfiQa18d7EWISWFBHUFEnZh1cgVmZNZ9PhMAAXXF6wNHSK/RuMD1fXhMWxAt0IqXT0YtwffXvWH/VH",
	"w2FT2ng67dGUi+L3KCB7j9xm9LAq7IMrfc24IDfWCk35I9ztAfmZVAFEX0tlCjpBuTbKT7ypG4nAeDiy",
	"Mnmap3T27XQ6cXt2v8N8Zp8cji+3OG4X9tZeNZf55fxG9gW2Wy9yhzW3GSDELIxxmxEzsJKK/5uLFRFg",
	"7qV6X7GowB29owkTtEc3mbAkmEpTj6eVYVHsW3sinyyq1k/okxzJh2CY2M1xj1a/nHiTL1Ku9Z/gBpcO",
	"21iqjUQG5O6F3moD6YGYOj2eKiw1zvfS+Pd13ibcFw1LxpOdwH4hhYDIBi0UJXND90SaY6D/eBKrFREN",
	"LhtPToPJus6jCENZJ5jsotYHbvQyT+qLO3oIgKqbp6wR7rqhV0NQO11kkEoxD9nnqjKMpw43mJg1MwU9",
	"YGbsN9dwoRt6MhyOQq6Lc+VyQQ2RFHEoCUdrFcMQr8XIuj+Gh6IjWie8t8tiT4apFZjj8pYUmJgrY+Zp",
	"QOPXwARRMhfxiVE8s8hFxVOeJDykfbgYKzc0DNRHmZJGRjIJkIx/Q3INcQPItWh7e3FNe/Tt5TUippY1",
	"28ctJ2FRwjewrwZ8418Ts1YyX62z3OB2X+Pg2uovzib90aM3qsAoJnTKu0vqapiBmGQseg/NIm34aMka",
	"C7Hwjm9AmIO7nX6CWxEq2rA06wjiZfioDt5f3vxwMZlMXvz1mbLiSq3qJNUNtAuRGj4DR7xXizWh1GK3",
	"C3M0U5YT/4uY8jn56ABnhMkiZMQvhSy622CXzfZX6FCOvuuPXzz6VMIHA0rYflQgl/Eva5VMOPTW8DLp",
	"D/uj0aQf3CXXASlXAqWAsRUJj4BcK7nhcbNsoBcyjbBGvmCNtlq19u8YH1WQtf5hX3Xx1PgTwnfGxSoo",
	"7hqLgYQZENG2kxyn/Renn8AaeETmuQoQ5Ns3r4iRZJknyW6TuLLk2phMzwaD+/v7voUTjuwLMAM3emCP",
	"XP2U54qHLO6Ku+BJuan61L7avrpsFsFexr5Fw1Vue1lf0rVwElr6S2GgHu3sO7/Nuk/6ZDrpTx/Lvx2s",
	"1ww9TeUqlHczm3VclCtutjfIWC6Unmf8J9ie52Yd6K5fX5H3sLWhRLuDf2Lkif8nYblZY7CNXGnboxwn",
	"rYG5uODgQf95cn59dfITbCsjMyuTPqBKXCylpUUpDIssJ0LKeIK+yDOs///mrdqPZFot62B2sYboPShy",
	"fn3V6kVZ9a3qyCQGq2XbccVcjcOm3g2oXdngiPZNUv83cbvmGuU4VGvCtAVjBMIolpCYGUYStvVs6VaM",
	"vHrOLdoufg8LEheXXv3f0G4Jj0Boe5b87l5f3aKXMX6UsUBmILTMVQR9qVYDP0kPcKw9OSYJG6ZHN6Ac",
	"kdJRf9gf4nBcjWWcziiywQRRxMzaQmJQqoe/VmBCObe1IVQ7ITpPbffOGoKLKMljNLG7UXD9Frv/2m2C",
	"1cJlZ1cxndEfwZTXgTap05nELaL88XBYwASES8qyLPHYG/yuXZrgUrFDxXjzztHCcIfKy13Z3XjEQFwr",
	"mZOtO1Fu1075mjVwHgKerTSe5cqidzhrUN7RdVs3kmLJV7nN/ypMFhd3LeO99C8yplgKBpS2OWtz8R94",
	"gkS72Lqukm+02aP7Rw5qWx0x/+o4m9Z7e/tF+gYWYiDXe8T6hlhdcKsbcfcn0XHUdWzRs2newbbRYs1+",
	"PEgCnixg4n7f2Q6uDgDjPI4JIwLudxdpoeE8jl+650gpoM3fZbx9sgPUbGk2icuoHB5a7hk9qex9Xigu",
	"nXZc0KOnTxg93H1nQIMrYS8Xibe4iwFN/6MD0X3eZ7t+L0PD4CP+7yp+cBhIwAQyrUv7nDDf6lYybZaI",
	"TUS40SUoGt45DV+SECc5ZM7T5zen1UBIQ5YyF/GOIf3e99ixdyCuMuTniC955Gy32BJutMt/g1H1Odmo",
	"E9D7osqX4IMffbsSzWdNFwhjXUxkF7cTLQ1g/lGxgMM/3Y0sdVboarkiQ2S5CWXumPUTJgh84PYKxe2h",
	"oNoil23CwM165ojqL5aOiqefCX7+9vlLiqdfAvI9iDqiuOXnQVHaH0z02hUHuedmTWRxf760KZS78GtF",
	"qPKC5WDy99rd6dY+KirEGYmxJldiT1aW8JSbRlJWflDgbqSL2+LRcHjgOqSdIP4cUke/59keZeRyqWGP",
	"NsNgjd0h3GenhWS2NPaijGtSVuCN/kJIIW2YMnPfSqiUOq7XfUChBSylgsdqBCJ+Yn2KiqGK2Dsia635",
	"3cz9sPkX26JRu3f9qrkRkFCq/2dLg2an2cE+sJFeAcLgu9rBf6ovUO0Hg4c/EkyZidau8C7aikd8GtiO",
	"ve2A9CkFTk0JHyTty44Sx7b9zW6NU+hgk1zmkdIKhW5uactnourgBxGftwZqweUIBxZtsC+NzaefR7i/",
	"JfEtafAD69D1yDsKvUjxZV/+eJpvfxr+GJovr8a+0vxXmn9Omv8fJuIj/gTj8xLxTTtkdPUEPmMgt6Ag",
	"tTjUzgSCfwpTxNIyfh7OBlzPs7XaUelA6dFnSgeCX3183nSgBdojYPQ1HTguHTgawvX7VUvJ9ZvVd3cY",
	"Dp20EGG/kpH9SH4DicxS+1dkxVfZ1SXgbDBIcBzWWbOz4dlwwDI+2IxoO5ZfKxnn7sPVwEJ6NnDZi72f",
	"7NfuV8sV78pNfjyIpPLU6RpTlpZpK9dOTUMruFSrPds2ZlIm2AqsoUJzXSemPXfnXi80tbqpe7h7+E8A",
	"AAD//xY7PiC4OAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
