// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bfirestone/speed-checker/ent/host"
	"github.com/bfirestone/speed-checker/ent/iperftest"
	"github.com/bfirestone/speed-checker/ent/predicate"
)

// IperfTestQuery is the builder for querying IperfTest entities.
type IperfTestQuery struct {
	config
	ctx        *QueryContext
	order      []iperftest.OrderOption
	inters     []Interceptor
	predicates []predicate.IperfTest
	withHost   *HostQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IperfTestQuery builder.
func (itq *IperfTestQuery) Where(ps ...predicate.IperfTest) *IperfTestQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit the number of records to be returned by this query.
func (itq *IperfTestQuery) Limit(limit int) *IperfTestQuery {
	itq.ctx.Limit = &limit
	return itq
}

// Offset to start from.
func (itq *IperfTestQuery) Offset(offset int) *IperfTestQuery {
	itq.ctx.Offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *IperfTestQuery) Unique(unique bool) *IperfTestQuery {
	itq.ctx.Unique = &unique
	return itq
}

// Order specifies how the records should be ordered.
func (itq *IperfTestQuery) Order(o ...iperftest.OrderOption) *IperfTestQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// QueryHost chains the current query on the "host" edge.
func (itq *IperfTestQuery) QueryHost() *HostQuery {
	query := (&HostClient{config: itq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(iperftest.Table, iperftest.FieldID, selector),
			sqlgraph.To(host.Table, host.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, iperftest.HostTable, iperftest.HostColumn),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IperfTest entity from the query.
// Returns a *NotFoundError when no IperfTest was found.
func (itq *IperfTestQuery) First(ctx context.Context) (*IperfTest, error) {
	nodes, err := itq.Limit(1).All(setContextOp(ctx, itq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{iperftest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *IperfTestQuery) FirstX(ctx context.Context) *IperfTest {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IperfTest ID from the query.
// Returns a *NotFoundError when no IperfTest ID was found.
func (itq *IperfTestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(1).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{iperftest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *IperfTestQuery) FirstIDX(ctx context.Context) int {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IperfTest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IperfTest entity is found.
// Returns a *NotFoundError when no IperfTest entities are found.
func (itq *IperfTestQuery) Only(ctx context.Context) (*IperfTest, error) {
	nodes, err := itq.Limit(2).All(setContextOp(ctx, itq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{iperftest.Label}
	default:
		return nil, &NotSingularError{iperftest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *IperfTestQuery) OnlyX(ctx context.Context) *IperfTest {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IperfTest ID in the query.
// Returns a *NotSingularError when more than one IperfTest ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *IperfTestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(2).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{iperftest.Label}
	default:
		err = &NotSingularError{iperftest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *IperfTestQuery) OnlyIDX(ctx context.Context) int {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IperfTests.
func (itq *IperfTestQuery) All(ctx context.Context) ([]*IperfTest, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryAll)
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IperfTest, *IperfTestQuery]()
	return withInterceptors[[]*IperfTest](ctx, itq, qr, itq.inters)
}

// AllX is like All, but panics if an error occurs.
func (itq *IperfTestQuery) AllX(ctx context.Context) []*IperfTest {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IperfTest IDs.
func (itq *IperfTestQuery) IDs(ctx context.Context) (ids []int, err error) {
	if itq.ctx.Unique == nil && itq.path != nil {
		itq.Unique(true)
	}
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryIDs)
	if err = itq.Select(iperftest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *IperfTestQuery) IDsX(ctx context.Context) []int {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *IperfTestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryCount)
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, itq, querierCount[*IperfTestQuery](), itq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (itq *IperfTestQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *IperfTestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryExist)
	switch _, err := itq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *IperfTestQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IperfTestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *IperfTestQuery) Clone() *IperfTestQuery {
	if itq == nil {
		return nil
	}
	return &IperfTestQuery{
		config:     itq.config,
		ctx:        itq.ctx.Clone(),
		order:      append([]iperftest.OrderOption{}, itq.order...),
		inters:     append([]Interceptor{}, itq.inters...),
		predicates: append([]predicate.IperfTest{}, itq.predicates...),
		withHost:   itq.withHost.Clone(),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// WithHost tells the query-builder to eager-load the nodes that are connected to
// the "host" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *IperfTestQuery) WithHost(opts ...func(*HostQuery)) *IperfTestQuery {
	query := (&HostClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	itq.withHost = query
	return itq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Timestamp time.Time `json:"timestamp,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IperfTest.Query().
//		GroupBy(iperftest.FieldTimestamp).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (itq *IperfTestQuery) GroupBy(field string, fields ...string) *IperfTestGroupBy {
	itq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IperfTestGroupBy{build: itq}
	grbuild.flds = &itq.ctx.Fields
	grbuild.label = iperftest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Timestamp time.Time `json:"timestamp,omitempty"`
//	}
//
//	client.IperfTest.Query().
//		Select(iperftest.FieldTimestamp).
//		Scan(ctx, &v)
func (itq *IperfTestQuery) Select(fields ...string) *IperfTestSelect {
	itq.ctx.Fields = append(itq.ctx.Fields, fields...)
	sbuild := &IperfTestSelect{IperfTestQuery: itq}
	sbuild.label = iperftest.Label
	sbuild.flds, sbuild.scan = &itq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IperfTestSelect configured with the given aggregations.
func (itq *IperfTestQuery) Aggregate(fns ...AggregateFunc) *IperfTestSelect {
	return itq.Select().Aggregate(fns...)
}

func (itq *IperfTestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range itq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, itq); err != nil {
				return err
			}
		}
	}
	for _, f := range itq.ctx.Fields {
		if !iperftest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *IperfTestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IperfTest, error) {
	var (
		nodes       = []*IperfTest{}
		withFKs     = itq.withFKs
		_spec       = itq.querySpec()
		loadedTypes = [1]bool{
			itq.withHost != nil,
		}
	)
	if itq.withHost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, iperftest.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IperfTest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IperfTest{config: itq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := itq.withHost; query != nil {
		if err := itq.loadHost(ctx, query, nodes, nil,
			func(n *IperfTest, e *Host) { n.Edges.Host = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (itq *IperfTestQuery) loadHost(ctx context.Context, query *HostQuery, nodes []*IperfTest, init func(*IperfTest), assign func(*IperfTest, *Host)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*IperfTest)
	for i := range nodes {
		if nodes[i].host_iperf_tests == nil {
			continue
		}
		fk := *nodes[i].host_iperf_tests
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(host.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "host_iperf_tests" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (itq *IperfTestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	_spec.Node.Columns = itq.ctx.Fields
	if len(itq.ctx.Fields) > 0 {
		_spec.Unique = itq.ctx.Unique != nil && *itq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *IperfTestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(iperftest.Table, iperftest.Columns, sqlgraph.NewFieldSpec(iperftest.FieldID, field.TypeInt))
	_spec.From = itq.sql
	if unique := itq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if itq.path != nil {
		_spec.Unique = true
	}
	if fields := itq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, iperftest.FieldID)
		for i := range fields {
			if fields[i] != iperftest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *IperfTestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(iperftest.Table)
	columns := itq.ctx.Fields
	if len(columns) == 0 {
		columns = iperftest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.ctx.Unique != nil && *itq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IperfTestGroupBy is the group-by builder for IperfTest entities.
type IperfTestGroupBy struct {
	selector
	build *IperfTestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *IperfTestGroupBy) Aggregate(fns ...AggregateFunc) *IperfTestGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the selector query and scans the result into the given value.
func (itgb *IperfTestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, itgb.build.ctx, ent.OpQueryGroupBy)
	if err := itgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IperfTestQuery, *IperfTestGroupBy](ctx, itgb.build, itgb, itgb.build.inters, v)
}

func (itgb *IperfTestGroupBy) sqlScan(ctx context.Context, root *IperfTestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*itgb.flds)+len(itgb.fns))
		for _, f := range *itgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*itgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IperfTestSelect is the builder for selecting fields of IperfTest entities.
type IperfTestSelect struct {
	*IperfTestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (its *IperfTestSelect) Aggregate(fns ...AggregateFunc) *IperfTestSelect {
	its.fns = append(its.fns, fns...)
	return its
}

// Scan applies the selector query and scans the result into the given value.
func (its *IperfTestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, its.ctx, ent.OpQuerySelect)
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IperfTestQuery, *IperfTestSelect](ctx, its.IperfTestQuery, its, its.inters, v)
}

func (its *IperfTestSelect) sqlScan(ctx context.Context, root *IperfTestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(its.fns))
	for _, fn := range its.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*its.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
