// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// IperfTest is the predicate function for iperftest builders.
type IperfTest func(*sql.Selector)

// SpeedTest is the predicate function for speedtest builders.
type SpeedTest func(*sql.Selector)
